<a href="https://colab.research.google.com/github/scw0310/ESAA/blob/main/ESAA_YB_week1_FRI_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [1]:
import numpy as np

A = np.random.random((5,3))
B = np.random.random((3,2))

print(A)
print(B)
print(np.dot(A, B))

[[0.72431638 0.68581508 0.3853574 ]
 [0.98216212 0.18423373 0.31681798]
 [0.80927157 0.09472219 0.6026909 ]
 [0.52248961 0.29292455 0.68907564]
 [0.85049166 0.0579234  0.08389781]]
[[0.37786581 0.84473722]
 [0.41185712 0.40448031]
 [0.47971822 0.39016972]]
[[0.74101519 1.03961049]
 [0.59898683 1.02780061]
 [0.63392988 0.95708682]
 [0.64863616 0.82870508]
 [0.3854752  0.77460523]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [4]:
matrix22 = np.arange(10)
matrix22[(matrix22 > 3) & (matrix22 < 8)] *= -1
print(matrix22)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9 ( 0+1+2+3+4-1)
10(0+1+2+3+4)

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

1,2,4,5 -> 합법적
3,6 -> 합법적

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

array(nan)
error
value error

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [5]:
import numpy as np

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

common_value = np.intersect1d(Z1, Z2)

print("Z1:", Z1)
print("Z2:", Z2)
print("common value:", common_value)

Z1: [2 9 7 3 8 3 0 9 1 6]
Z2: [1 7 9 7 6 3 0 4 4 2]
common value: [0 1 2 3 6 7 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [6]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [11]:
A = np.array([1, 2, 3], dtype=np.float64)
B = np.array([4, 5, 6])

np.add(A, B, out=A)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, A, out=A)

print(A)

[ 6.25 12.25 20.25]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [13]:
array30 = np.random.random(5) * 100

# //이용
int1 = array30 // 1

# %이용
int2 = array30 - (array30 % 1)

print("Original array:", array30)
print("Integer part using // 1:", int1)
print("Integer part using %:", int2)

Original array: [18.78613743 34.1274662  79.20341767 24.91398085 80.06296579]
Integer part using // 1: [18. 34. 79. 24. 80.]
Integer part using %: [18. 34. 79. 24. 80.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix31 = np.arange(5)
matrix31 = np.tile(matrix, (5, 1))

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [14]:
vector32 = np.random.random(10)
vector32.sort()
print(vector32)

[0.0429874  0.13727322 0.21850835 0.39115725 0.4216573  0.46823246
 0.69298407 0.74782998 0.85713549 0.96346471]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [16]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

np.array_equal(A, B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [17]:
cartesian = np.random.random((10, 2)) * 10

radius = np.sqrt(cartesian[:, 0]**2 + cartesian[:, 1]**2)

angle = np.arctan2(cartesian[:, 1], cartesian[:, 0])

polar = np.vstack((radius, angle)).T

print("Cartesian coordinates:")
print(cartesian)
print("\nPolar coordinates:")
print(polar)

Cartesian coordinates:
[[8.25469797 0.52273736]
 [4.85635147 1.51521668]
 [1.44223342 7.82765199]
 [3.65149229 6.45032779]
 [1.95652568 5.58655829]
 [1.48076158 3.30411344]
 [0.33866975 9.09914025]
 [3.68792867 6.0125325 ]
 [8.64594563 6.77650255]
 [5.91437062 8.26732401]]

Polar coordinates:
[[ 8.27123285  0.0632416 ]
 [ 5.08724201  0.30243586]
 [ 7.95940783  1.38859125]
 [ 7.41216059  1.05568085]
 [ 5.91925893  1.23392533]
 [ 3.62074861  1.14947609]
 [ 9.10544071  1.53359353]
 [ 7.05346475  1.02060129]
 [10.98514281  0.66477095]
 [10.16505908  0.94981523]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [25]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.90362775 0.28859014 0.1918338  0.13987918 0.22816157 0.48024462
 0.         0.80945725 0.65474794 0.78756309]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [26]:
Z = np.arange(100)
v = np.random.uniform(0, 100)

distances = np.abs(Z - v)
closest_value = Z[np.argmin(distances)]

print("Vector Z:", Z)
print("Scalar v:", v)
print("Closest value in Z to v:", closest_value)

Vector Z: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Scalar v: 40.689626242222296
Closest value in Z to v: 41


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [27]:
Z = np.arange(9).reshape(3, 3)

for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [32]:
#n=5, p=10, value=1인 경우

Z = np.zeros((5, 5))
print(Z)

np.put(Z, np.random.choice(5 * 5, 10, replace=False), 1)
print(Z)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [33]:
Z = np.random.randint(0, 10, (3, 3))

In [39]:
# column 1
Z1 = Z[np.argsort(Z[:, 0])]
print(Z1)

[[3 4 2]
 [7 4 5]
 [9 4 4]]


In [36]:
# column 2
Z2 = Z[np.argsort(Z[:, 1])]
print(Z2)

[[3 4 2]
 [9 4 4]
 [7 4 5]]


In [38]:
# column 3
Z3 = Z[np.argsort(Z[:, 2])]
print(Z3)

[[3 4 2]
 [9 4 4]
 [7 4 5]]
