# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
null_vector_memory = null_vector.nbytes
print(null_vector_memory)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector6 = np.arange(start=10, stop=50)
print(vector6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vector7 = vector6[::-1]
print(vector7)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix8 = np.arange(0, 9).reshape(3, 3)
print(matrix8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
vector9 = np.array([1,2,0,0,4,0])
nonzero_vector9 = np.where(vector9 != 0)
print(nonzero_vector9)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
matrix10 = np.identity(3)
print(matrix10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
matrix11 = np.random.random((3,3,3))
print(matrix11)

[[[0.47702121 0.58662166 0.59536747]
  [0.3507566  0.5067094  0.71479134]
  [0.32160029 0.28683617 0.76118227]]

 [[0.37055324 0.44624192 0.54903143]
  [0.55338026 0.6220815  0.77524828]
  [0.23174381 0.76370886 0.51861321]]

 [[0.13654135 0.67286816 0.22281929]
  [0.10728173 0.38847392 0.41855927]
  [0.55086561 0.60011034 0.38169409]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
matrix12 = np.random.random((10, 10))
print(matrix12)
print('min :',np.min(matrix12), 'max :',np.max(matrix12))

[[0.81922818 0.24572754 0.73866443 0.06885862 0.63826328 0.12382422
  0.19026664 0.18398723 0.5449452  0.46236602]
 [0.8203021  0.39275005 0.93345453 0.1008105  0.57925523 0.67049795
  0.67707297 0.09748527 0.19629398 0.01892643]
 [0.24285108 0.8842453  0.60912636 0.49747709 0.98547111 0.19521616
  0.45512251 0.40978951 0.68207547 0.17437903]
 [0.13575615 0.28702917 0.34863191 0.72729654 0.50761827 0.58053891
  0.48427223 0.44147269 0.89288171 0.84458978]
 [0.94931337 0.89060737 0.72911929 0.22505269 0.16741354 0.83059838
  0.780269   0.75971816 0.42135963 0.82118771]
 [0.3341977  0.56347648 0.83510196 0.82289238 0.66555785 0.57928455
  0.33256017 0.43178118 0.62288844 0.85333394]
 [0.09237543 0.47474341 0.62221723 0.54166813 0.01497455 0.83470356
  0.10879908 0.80041356 0.96803956 0.78606526]
 [0.57951412 0.41311865 0.89563799 0.91634518 0.70661414 0.99543397
  0.63128724 0.54657664 0.87659531 0.29164568]
 [0.05722652 0.73999945 0.21661492 0.52294777 0.9383021  0.89147526
  0.03782742

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
matrix13 = np.random.random(30)
print('mean :',np.mean(matrix13))

mean : 0.4552167121060035


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
matrix14 = np.ones((4, 4))
matrix14[1:-1, 1:-1] = 0
print(matrix14)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, False, False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
matrix16 = np.zeros((5,5))
matrix16[1, 0] = 1
matrix16[2, 1] = 2
matrix16[3, 2] = 3
matrix16[4, 3] = 4
print(matrix16)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix17 = np.zeros((8, 8))
matrix17[::2, ::2] = 1
matrix17[1::2, 1::2] = 1
print(matrix17)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(100, shape=(6, 7, 8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
matrix19 = np.random.random((5,5))
X_bar = matrix19.mean()
std = matrix19.std()
normalize_matrix19 = (matrix19 - X_bar)/std
print(normalize_matrix19)

[[ 0.89556182 -1.5026314  -0.45956356 -0.14653282 -0.45369778]
 [ 1.13670254  1.6635183  -1.164875   -1.38427063 -1.79611669]
 [ 0.89139786  0.6672095   0.86149746 -0.56264267 -1.30544808]
 [ 1.28420292  1.14751462  0.07918548 -1.22563708 -0.31928208]
 [ 0.23757698  0.36227598  1.34756794 -0.53183244  0.27831885]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
rgba_dtype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(rgba_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A =  np.arange(1, 16).reshape(5, 3)
print(A)
B = np.arange(1, 7)[::-1].reshape(3, 2)
print(B)

print(np.dot(A, B))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[6 5]
 [4 3]
 [2 1]]
[[ 20  14]
 [ 56  41]
 [ 92  68]
 [128  95]
 [164 122]]
